base: registry.vanillaos.org/vanillaos/pico:main
name: Vanilla Core
singlelayer: false
labels:
  maintainer: Vanilla OS Contributors
args:
  DEBIAN_FRONTEND: noninteractive
runs:
- echo 'APT::Install-Recommends "0";' > /etc/apt/apt.conf.d/01norecommends

modules:
- name: mandb
  type: shell
  commands:
  - apt update
  - apt install -y man-db
  - mandb -c
  
- name: abroot
  type: go # only during development, switch to the tar module for production
  buildvars:
    GO_OUTPUT_BIN: /usr/bin/abrootv2
  source:
    type: git
    branch: 2.0-oci-support
    url: https://github.com/Vanilla-OS/ABRoot.git
    commit: 109c001b70c066590fcd9bfaaa4d8591f11e9334
  modules:
  - name: abroot-deps # remove this module in production
    type: apt
    source:
      packages:
        - pkg-config
        - golang-go
        - libbtrfs-dev
        - libdevmapper-dev
        - libgpgme-dev
        - build-essential

- name: packages-modules
  type: gen-modules
  path: modules

- name: cleanup
  type: shell
  commands:
  - apt remove build-essential golang-1.19-src -y # remove this line in production
  - apt autoremove -y
  - apt clean
