base: debian:sid-slim
name: Vanilla Core
singlelayer: false
labels:
  maintainer: Vanilla OS Contributors
args:
  DEBIAN_FRONTEND: noninteractive
runs:
- echo 'APT::Install-Recommends "0";' > /etc/apt/apt.conf.d/01norecommends

modules:
- name: init-setup
  type: shell
  commands:
  - rm /etc/dpkg/dpkg.cfg.d/*
  # - dpkg -l | grep ^ii | cut -d' ' -f3 | xargs apt-get install -y --reinstall
  - rm -r /var/lib/apt/lists/*
  # - mandb -c
  - rm -rf /etc/apt/sources.list.d
  - mv /etc/apt/sources.list.d.new /etc/apt/sources.list.d
  - ls /etc/apt/sources.list.d
  - apt-key add /vanilla.key
  - apt update
  - apt install --reinstall -y $(dpkg --get-selections | awk '{if ($2=="install") print $1}')
  - mandb -c
  modules:
  - name: apt-essentials
    type: apt
    source:
      packages:
        - apt-utils
        - apt-transport-https
        - ca-certificates
        - man-db
        - gnupg2
        - build-essential
    modules:
    - name: apt-update
      type: shell
      commands:
      - apt update

- name: abroot
  type: go
  buildvars:
    GO_OUTPUT_BIN: /usr/bin/abrootv2
  source:
    type: git
    branch: 2.0-oci-support
    url: https://github.com/Vanilla-OS/ABRoot.git
    commit: 109c001b70c066590fcd9bfaaa4d8591f11e9334
  modules:
  - name: abroot-deps
    type: apt
    source:
      packages:
        - pkg-config
        - golang-go
        - libbtrfs-dev
        - libdevmapper-dev
        - libgpgme-dev

- name: packages-modules
  type: gen-modules
  path: modules

- name: cleanup
  type: shell
  commands:
  - apt remove build-essential golang-1.19-src -y
  - apt autoremove -y
  - apt clean
