base: registry.vanillaos.org/vanillaos/pico:main
name: Vanilla Core
singlelayer: false
labels:
  maintainer: Vanilla OS Contributors
args:
  DEBIAN_FRONTEND: noninteractive
runs:
- echo 'APT::Install-Recommends "0";' > /etc/apt/apt.conf.d/01norecommends

modules:
- name: mandb
  type: shell
  commands:
  - apt update
  - apt install -y man-db
  - mandb -c
  
- name: abroot
  type: shell
  source:
    type: tar
    # switch to production build once in production
    url: https://github.com/Vanilla-OS/ABRoot/releases/download/continuous/abrootv2.tar.gz
  commands:
  - mkdir -p /usr/bin
  - cp /sources/abrootv2 /usr/bin/abrootv2
  - chmod +x /usr/bin/abrootv2
  
- name: packages-modules
  type: gen-modules
  path: modules

- name: cleanup
  type: shell
  commands:
  - apt autoremove -y
  - apt clean
