name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Prepare
      run: sh prepare.sh

    - name: Build the Docker image
      run: docker image build -f Containerfile --tag vanillaos/core:${{ github.ref_name }} .

    - name: Push To Registry
      uses: redhat-actions/push-to-registry@v2.7
      with:
        image: vanillaos/core
        tags: ${{ github.ref_name }}
        registry: ${{ secrets.NEXUS_REGISTRY }}
        username: ${{ secrets.NEXUS_USER }}
        password: ${{ secrets.NEXUS_PSW }}
        tls-verify: false
